; SIMPLE CP/M HELLO WORLD PROGRAM IN ASM
; THIS PROGRAM PRINTS 'HELLO, WORLD!' TO THE CONSOLE

ORG 100H           ; CP/M PROGRAM LOAD ADDRESS

START:
    MVI  C, 9       ; BDOS FUNCTION 9: PRINT STRING
    LXI  D, MSG     ; DE POINTS TO STRING
    CALL 5          ; CALL BDOS
    RET             ; RETURN TO CP/M

MSG:
    DB 'HELLO, WORLD!$'
